service: serverless-hello-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.index  # file.function
    events:
      - http:
          path: hello
          method: GET

plugins:
  - serverless-offline
