service: serverless-started-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: { "Fn::GetAtt": [ "usersTable", "Arn" ] }  # Better
          #Resource: arn:aws:dynamodb:us-east-1:471893938953:table/usersTable

functions:
  hello:
    handler: users/get.index  # file.function
    events:
      - http:
          path: /hello
          method: GET
  get-user:
    handler: users/get.getUser  # file.function
    events:
      - http:
          path: /users/{id}
          method: GET
  get-users:
    handler: users/get.getUsers  # file.function
    events:
      - http:
          path: /users
          method: GET
  create-user:
    handler: users/create.store  # file.function
    events:
      - http:
          path: /users
          method: POST

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      docker: false
      migrate: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
